# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeParticipant', models.CharField(max_length=20)),
                ('awayParticipant', models.CharField(max_length=20)),
                ('homeScore1', models.IntegerField(max_length=2)),
                ('awayScore1', models.IntegerField(max_length=2)),
                ('homeScore2', models.IntegerField(max_length=2)),
                ('awayScore2', models.IntegerField(max_length=2)),
                ('homeScore3', models.IntegerField(max_length=2)),
                ('awayScore3', models.IntegerField(max_length=2)),
            ],
        ),
    ]
