# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='awayParticipant',
            new_name='aP',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='homeParticipant',
            new_name='hP',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayScore1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayScore2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayScore3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeScore1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeScore2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeScore3',
        ),
        migrations.AddField(
            model_name='match',
            name='aS1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='aS2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='aS3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='hS1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='hS2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='hS3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
