# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20171221_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hS1', models.IntegerField()),
                ('aS1', models.IntegerField()),
                ('hS2', models.IntegerField()),
                ('aS2', models.IntegerField()),
                ('hS3', models.IntegerField()),
                ('aS3', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='aS1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='aS2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='aS3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='hS1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='hS2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='hS3',
        ),
        migrations.AddField(
            model_name='result',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Match'),
        ),
    ]
